### ISSUE TITLE
Latest version of PHP (5.6.13)

### ISSUE THREAD

**Issue by martinezdelariva** [snap-ci/php-build#1]
Hola!
It would be nice to be able to use latest version of PHP in the build system. 
At the moment is 5.6.13 and also the upcoming PHP 7.
Thanks.

**Comment by akshaykarle** [comment]
Hey @martinezdelariva thanks for pointing that out. We'll look into adding support for the latest php versions soon.

**Comment by mceire** [comment]
:+1: That would be amazing!

**Comment by monteiro** [comment]
+1

**Comment by cgilj** [comment]
+1

**Comment by mgonzalezbaile** [comment]
:+1:

**Comment by ese** [comment]
++

**Comment by martinezdelariva** [comment]
@akshaykarle I saw commits related to this issue. Do you know when are new PHP version be available to be selected in SnapCI configuration?

Thanks.

**Comment by martasma** [comment]
+1

**Comment by j-d** [comment]
+1
Yes please!

**Comment by suziejprince** [comment]
Hey all 

We see your +1s. We have this story on our backlog. We will update you when we get to it.

You can also get in touch as support@snap-ci.com.

Thanks! 
Suzie

**Comment by martinezdelariva** [comment]
Thanks so much for the feedback.

**Comment by akshaykarle** [comment]
We have packaged the new phps. We still don't show them from the UI, but you can use them by just installing them using yum while we still update our UI to show the new versions. You install the phps using yum. For eg- if you want to install php 7, you can install it as follows:

```
sudo yum install php-7.0.3.x86_64 
export PATH=/opt/local/php/7.0.3/bin:$PATH
```

Hope this gets your builds running. If you have any questions, please get in touch with us on support@snap-ci.com
